---
title: "Project Based - Project Two"
author: "Becca Richards"
date: "2023-03-06"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load the mlbench package which has the BreastCancer data set we will be using
#install.packages("mlbench")
library(mlbench)
require(mlbench)
```

```{r}
#load the required packages
library(klaR)
library(nnet)
library(neuralnet)
library(rpart)
library(rpart.plot)
library(e1071)
```

```{r}
# load the data set
data(BreastCancer)
ls(BreastCancer)
```

```{r}
# some algorithms don't like missing values, so remove rows with missing values
BreastCancer <- na.omit(BreastCancer) 
# remove the unique identifier, which is useless and would confuse the machine learning algorithms
BreastCancer$Id <- NULL 
head(BreastCancer)
str(BreastCancer)
df2 <- data.frame(sapply(BreastCancer[1:9], function(x) as.numeric(as.character(x))))
z <- scale(df2[,1:9],center=TRUE,scale=TRUE)
head(z)
```

```{r}
#create svm model
mysvm <- svm(Class ~ ., BreastCancer)
mysvm.pred <- predict(mysvm, BreastCancer)
table(mysvm.pred,BreastCancer$Class)
str(mysvm)
```

```{r}
#create NaiveBayes model
mynb <- NaiveBayes(Class ~ ., BreastCancer)
str(mynb)
mynb$tables
mynb$apriori
mynb.pred <- predict(mynb,BreastCancer)
head(mynb.pred$class)
table(mynb.pred$class,BreastCancer$Class)
str(mysvm.pred)
str(mynb.pred)
```

```{r}
#create Neural Network model
str(BreastCancer)
for (i in c(1:9)){
BreastCancer[,i] <-(as.numeric(BreastCancer[,i])-min(as.numeric(BreastCancer[,i]))) /
  (max(as.numeric(BreastCancer[,i]))-min(as.numeric(BreastCancer[,i])))
}
mynnet <- neuralnet(Class ~ ., BreastCancer, hidden=c(5,4))
head(BreastCancer)
head(BreastCancer$Class)
mynnet.pred <- predict(mynnet,BreastCancer,type="class")
str(mynnet.pred)
str(BreastCancer)
head(mynnet.pred[,])
mynnetClass <- ifelse(mynnet.pred[,1]>.5, "benign", "malignant")
head(mynnetClass)
head(BreastCancer)
bcClass=ifelse(BreastCancer$Class=="benign", 1, 0)
library(MASS)
table(mynnetClass,BreastCancer$Class)
```

```{r}
#create Decision Tree model
mytree <- rpart(Class ~ ., BreastCancer)
plot(mytree); text(mytree) 
summary(mytree)
mytree.pred <- predict(mytree,BreastCancer,type="class")
table(mytree.pred,BreastCancer$Class)
str(mytree)
rpart.rules(mytree)
rpart.plot(mytree)
```

```{r}
#create Leave-1-Out Cross Validation (LOOCV)
ans <- numeric(length(BreastCancer[,1]))
for (i in 1:length(BreastCancer[,1])) {
  mytree <- rpart(Class ~ ., BreastCancer[-i,])
  mytree.pred <- predict(mytree,BreastCancer[i,],type="class")
  ans[i] <- mytree.pred
}
ans <- factor(ans,labels=levels(BreastCancer$Class))
table(ans,BreastCancer$Class)
```

```{r}
#create Quadratic Discriminant Analysis
library(MASS)
library(MASS)
myqda <- qda(Species ~ ., iris)
myqda.pred <- predict(myqda, iris)
table(myqda.pred$class,iris$Species)

myqda <- qda(Class ~ ., BreastCancer)
myqda.pred <- predict(myqda, BreastCancer)
head(myqda.pred$class)
table(myqda.pred$class,BreastCancer$Class)
```

```{r}
#Regularized Discriminant Analysis
library(klaR)
myrda <- rda(Class ~ ., BreastCancer)
myrda.pred <- predict(myrda, BreastCancer)

table(myrda.pred$class,BreastCancer$Class)
```

```{r}
#create Random Forests model
library(randomForest)
myrf <- randomForest(Class ~ ., BreastCancer)
myrf.pred <- predict(myrf, BreastCancer)
head(myrf.pred)
table(myrf.pred, BreastCancer$Class)
combine.classes<-data.frame(myrf.pred, myrda.pred$class,myqda.pred, 
                            mytree.pred,mynnetClass,mysvm.pred, mynb.pred$class, BreastCancer$Class)
head(combine.classes)
head(myrf.pred)
head(myrda.pred)
```

```{r}
#make all predictions same data type (binary numeric)
combine.classes$myrf.pred<-ifelse(combine.classes$myrf.pred=="benign", 0, 1)
combine.classes[,2]<-ifelse(combine.classes[,2]=="benign", 0, 1)
combine.classes[,3]<-ifelse(combine.classes[,3]=="benign", 0, 1)
combine.classes[,4]<-ifelse(combine.classes[,4]=="benign", 0, 1)
combine.classes[,5]<-ifelse(combine.classes[,5]=="benign", 0, 1)
combine.classes[,6]<-ifelse(combine.classes[,6]=="benign", 0, 1)
combine.classes[,7]<-ifelse(combine.classes[,7]=="benign", 0, 1)
combine.classes[,8]<-ifelse(combine.classes[,8]=="benign", 0, 1)
combine.classes[,9]<-ifelse(combine.classes[,9]=="benign", 0, 1)
combine.classes[,10]<-ifelse(combine.classes[,10]=="benign", 0, 1)
str(combine.classes)
```

```{r}
#view table of combined model predictions
combine.cl<-combine.classes[, -c(7,8)]
majority.vote=rowSums(combine.classes[,-c(7,8)])
head(majority.vote)
head(combine.cl)
```

```{r}
#use combined class table to assign majority vote for benign or malignant
combine.classes[,7]<-rowSums(combine.classes[,-c(7,8)])
combine.classes[,8]<-ifelse(combine.classes[,7]>=4, "malignant", "benign")
table(combine.classes[,8], BreastCancer$Class)
decTree<-rpart(BreastCancer.Class~., combine.classes)
str(decTree)
decTree
summary(decTree)
rpart.rules(decTree)
```

```{r}
# summarize differences between modes
summary(combine.classes)
```










